---
deployment:
  tasks:
    # 1. Deploy compiled frontend files to public_html
    - /bin/cp -R frontend/dist/* /home3/mwalimua/public_html/

    # 2. Deploy backend dist folder (so it keeps the 'dist' folder structure for your server.js startup file)
    - /bin/cp -R backend/dist /home3/mwalimua/backend/

    # 3. Deploy configuration files to the backend root directory
    - /bin/cp backend/package.json /home3/mwalimua/backend/
    - /bin/cp backend/package-lock.json /home3/mwalimua/backend